# Generated by Django 5.0.3 on 2024-04-06 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Babysitter',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('hourly_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating', models.IntegerField()),
                ('experience_years', models.IntegerField()),
                ('documents_submitted', models.BooleanField()),
                ('education_level', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=80)),
                ('neiborhood', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(max_length=1)),
                ('description', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('like', 'Like'), ('unlike', 'Unlike')], max_length=10)),
                ('babysitter_cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.babysitter')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('neiborhood', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(max_length=1)),
                ('favorited', models.ManyToManyField(blank=True, default=None, related_name='favorited', to='base.babysitter')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
