# Generated by Django 5.0.4 on 2024-04-06 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parent",
            name="favorited",
        ),
        migrations.AddField(
            model_name="babysitter",
            name="favorited",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="favorited",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
