# Generated by Django 5.0.3 on 2024-05-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Indisponível', 'Indisponível'), ('Pendente', 'Pendente')], max_length=15),
        ),
    ]
