# Generated by Django 5.0.3 on 2024-05-29 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_message_converstions'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Babysitter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.babysitter'),
        ),
        migrations.DeleteModel(
            name='Converstions',
        ),
    ]
