# Generated by Django 5.0.4 on 2024-05-31 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babysitter',
            name='rating',
        ),
        migrations.CreateModel(
            name='BabysitterRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('babysitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.babysitter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
