name: Build and deploy Python app to Azure Web App - BabysitEase-fds

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          cd BabysitEase
          pip install -r requirements.txt
          npm ci
          cd ..

      - name: Run migrations and Cypress tests
        run: |
          source venv/bin/activate
          cd BabysitEase
          python manage.py migrate
          python manage.py runserver &
          sleep 5
          npx cypress run
          cd ..

      - name: Clean testing files
        run: |
          cd BabysitEase/
          rm .env db.sqlite3 cypress.config.js package-lock.json package.json
          rm -rf cypress node_modules
          cd ..

      - name: Zip artifact for deployment
        run: |
          source venv/bin/activate
          cd BabysitEase/
          zip -r release.zip .
          cd ..
          mv BabysitEase/release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B9EE704FD5B145B683611230ADDDDE45 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_00BDC757F1164FABA7383764330EF30C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4AE2901977C64EF79BD1BE15D49E5FF0 }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "BabysitEase-fds"
          slot-name: "Production"
