# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - babysitease

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r BabysitEase/requirements.txt
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node.js dependencies
        run: |
          cd BabysitEase
          npm install -g n
          npm ci

      - name: Run local server
        run: |
          cd BabysitEase
          python manage.py migrate
          python manage.py runserver &
          sleep 5
          npx cypress run

      - name: Cleaning testing files
        run: |
          cd BabysitEase/
          rm db.sqlite3
          rm .env
          cd ..

      - name: Zip artifact for deployment
        run: |
          cd BabysitEase/
          zip release.zip ./* -r
          cd ..
          mv BabysitEase/release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E20FAF9F14ED461B82A18ACA9BD942F2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1A0058BE2D574272AEF714B20547A332 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FE5D80A1B3CA455D9952FB5A93BA415D }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'babysitease'
          slot-name: 'Production'
